import { User, UserRole } from './user.model';

export const USERS_DATA: User[] = [
  {
    id: 'U101',
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@example.com',
    role: UserRole.Owner,
    isActive: true,
    createdDate: new Date('2024-01-15T10:00:00Z'),
    optInToDirectory: true,
    showEmailInDirectory: true,
  },
  {
    id: 'U102',
    firstName: 'Bob',
    lastName: 'Johnson',
    email: 'bob.j@example.com',
    role: UserRole.Tenant,
    isActive: true,
    createdDate: new Date('2024-02-20T11:30:00Z'),
    optInToDirectory: true,
    showEmailInDirectory: false,
  },
  {
    id: 'U103',
    firstName: 'Charlie',
    lastName: 'Brown',
    email: 'charlie.b@example.com',
    role: UserRole.SecurityGuard,
    isActive: false,
    createdDate: new Date('2024-03-01T08:00:00Z'),
    lastModifiedDate: new Date('2024-03-10T14:00:00Z'),
    optInToDirectory: false,
    showEmailInDirectory: false,
  },
  {
    id: 'U104',
    firstName: 'Diana',
    lastName: 'Prince',
    email: 'diana.p@example.com',
    role: UserRole.PropertyManager,
    isActive: true,
    createdDate: new Date('2024-04-05T13:45:00Z'),
    optInToDirectory: true,
    showEmailInDirectory: true,
  },
  {
    id: 'U105',
    firstName: 'Eve',
    lastName: 'Adams',
    email: 'eve.a@example.com',
    role: UserRole.SuperAdmin,
    isActive: true,
    createdDate: new Date('2023-11-01T09:00:00Z'),
    optInToDirectory: false,
    showEmailInDirectory: false,
  },
];