import { Component, OnInit, signal } from '@angular/core';
import { Store } from '@ngrx/store';
import * as BookingsActions from '../store/bookings.actions';
import * as BookingsSelectors from '../store/bookings.selectors';
import { Observable } from 'rxjs';
import { Booking } from '../models/bookings.model';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

@Component({
  selector: 'app-bookings',
  templateUrl: './bookings.component.html',
  styleUrl: './bookings.component.scss',
  standalone: false
})
export class BookingsComponent implements OnInit {
  public selectedDate = signal<Date>(new Date());
  public bookings$: Observable<Booking[]>;
  public loading$: Observable<boolean>;
  public error$: Observable<any>;

  public newBookingForm = new FormGroup({
    amenity: new FormControl('', Validators.required),
    resident: new FormControl('', Validators.required),
    start: new FormControl<Date | null>(null, Validators.required),
    end: new FormControl<Date | null>(null, Validators.required),
    status: new FormControl<'Confirmed' | 'Pending' | 'Cancelled'>('Pending', Validators.required)
  });

  constructor(private store: Store) {
    this.bookings$ = this.store.select(BookingsSelectors.selectAllBookings);
    this.loading$ = this.store.select(BookingsSelectors.selectBookingsLoading);
    this.error$ = this.store.select(BookingsSelectors.selectBookingsError);
  }

  public ngOnInit(): void {
    this.store.dispatch(BookingsActions.loadBookings());
  }

  public getSeverity(status: 'Confirmed' | 'Pending' | 'Cancelled'): 'success' | 'warn' | 'danger' {
    switch (status) {
      case 'Confirmed': return 'success';
      case 'Pending': return 'warn';
      case 'Cancelled': return 'danger';
      default: return 'warn';
    }
  }

  public getBookingsForSelectedDate(): Observable<Booking[]> {
    return this.store.select(BookingsSelectors.selectBookingsForDate(this.selectedDate()));
  }

  public hasBookingsForDate(date: Date): boolean {
    let hasBookings = false;
    this.store.select(BookingsSelectors.selectBookingsForDate(date)).subscribe(bookings => {
      if (bookings.length > 0) {
        hasBookings = true;
      }
    }).unsubscribe();
    return hasBookings;
  }

  public onDateSelect(event: Date): void {
    this.selectedDate.set(event);
  }

  public onSubmitNewBooking(): void {
    if (this.newBookingForm.valid) {
      const formValue = this.newBookingForm.value;
      const newBooking: Booking = {
        id: '', // ID will be generated by service
        amenity: formValue.amenity!,
        resident: formValue.resident!,
        start: formValue.start!,
        end: formValue.end!,
        status: formValue.status!
      };
      this.store.dispatch(BookingsActions.addBooking({ booking: newBooking }));
      this.newBookingForm.reset();
    }
  }
}
