import { Unit, UnitStatus } from './unit.model';

export const UNITS_DATA: Unit[] = [
  {
    id: 'U1',
    unitNumber: '101',
    name: 'Tower A, Unit 101',
    building: 'Tower A',
    floor: 1,
    squareFootage: 800,
    beds: 1,
    baths: 1,
    address: '123 Ocean Drive',
    city: 'Miami',
    state: 'FL',
    zipCode: '33101',
    createdDate: new Date('2024-01-01'),
    status: UnitStatus.OwnerOccupied,
    ownerName: 'Alice Smith',
    ownerContact: 'alice@example.com',
  },
  {
    id: 'U2',
    unitNumber: '203',
    name: 'Tower A, Unit 203',
    building: 'Tower A',
    floor: 2,
    squareFootage: 1200,
    beds: 2,
    baths: 2,
    address: '123 Ocean Drive',
    city: 'Miami',
    state: 'FL',
    zipCode: '33101',
    createdDate: new Date('2024-02-15'),
    status: UnitStatus.Tenanted,
    ownerName: 'Bob Johnson',
    ownerContact: 'bob@example.com',
    tenantName: 'Charlie Brown',
    tenantContact: 'charlie@example.com',
  },
  {
    id: 'U3',
    unitNumber: '305',
    name: 'Tower B, Unit 305',
    building: 'Tower B',
    floor: 3,
    squareFootage: 1000,
    beds: 2,
    baths: 1,
    address: '125 Ocean Drive',
    city: 'Miami',
    state: 'FL',
    zipCode: '33101',
    createdDate: new Date('2024-03-10'),
    status: UnitStatus.Vacant,
    ownerName: 'David Lee',
    ownerContact: 'david@example.com',
  },
  {
    id: 'U4',
    unitNumber: '402',
    name: 'Tower B, Unit 402',
    building: 'Tower B',
    floor: 4,
    squareFootage: 1500,
    beds: 3,
    baths: 2,
    address: '125 Ocean Drive',
    city: 'Miami',
    state: 'FL',
    zipCode: '33101',
    createdDate: new Date('2024-04-05'),
    status: UnitStatus.OwnerOccupied,
    ownerName: 'Eve Davis',
    ownerContact: 'eve@example.com',
  },
];
